version: 0.2

phases:
  install:
    commands:
      - echo Installing...

  build:
    commands:
      - echo Building website...

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  base-directory: .
